### ISSUE TITLE
Install issue on Fedora

### ISSUE THREAD

**Issue by stonega** [harmonoid/harmonoid#132]
**Describe the bug**
The app can not be installed on Fedora 35 beta
I am not sure if this issue only exist on 35, which is still on beta stage, or on all Fedora os.

**To Reproduce**
1. Errors when install  rpm package 
```
RPM % sudo dnf install harmonoid-linux-x86_64.rpm
[sudo] password for stone: 
Last metadata expiration check: 1:44:40 ago on Sat 30 Oct 2021 10:08:35 AM CST.
Error: 
 Problem: conflicting requests
  - nothing provides libbitsdojo_window_linux_plugin.so()(64bit) needed by harmonoid-0.1.8-2.x86_64
  - nothing provides libdart_discord_rpc_plugin.so()(64bit) needed by harmonoid-0.1.8-2.x86_64
  - nothing provides libfile_selector_linux_plugin.so()(64bit) needed by harmonoid-0.1.8-2.x86_64
  - nothing provides libflutter_acrylic_plugin.so()(64bit) needed by harmonoid-0.1.8-2.x86_64
  - nothing provides libflutter_linux_gtk.so()(64bit) needed by harmonoid-0.1.8-2.x86_64
  - nothing provides libflutter_media_metadata_plugin.so()(64bit) needed by harmonoid-0.1.8-2.x86_64
  - nothing provides liblibwinmedia_plugin.so()(64bit) needed by harmonoid-0.1.8-2.x86_64
  - nothing provides liburl_launcher_linux_plugin.so()(64bit) needed by harmonoid-0.1.8-2.x86_64
(try to add '--skip-broken' to skip uninstallable packages)

```
2. Erros whrn running AppImage
```
RPM % ./harmonoid-linux-x86_64.AppImage 
./harmonoid: error while loading shared libraries: libmediainfo.so.0: cannot open shared object file: No such file or directory
```
**Expected behavior**
Install and work normally.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Fedora 
 - Version 35

**Smartphone (please complete the following information):**

**Comment by prateekmedia** [comment]
Looks like issue with `alien` tool.

**Comment by alexmercerind** [comment]
Now, we use `libmpv` for playback & parsing. Latest release & downloads: [v0.2.0](https://github.com/harmonoid/harmonoid/releases/tag/v0.2.0).

<table>
<tr>
<td>
<img src='https://github.com/harmonoid/harmonoid/raw/assets/linux_full/0.jpeg?raw=true'></img>
</td>
<td>
<img src='https://github.com/harmonoid/harmonoid/raw/assets/linux_full/4.jpeg?raw=true'></img>
</td>
</tr>
</table>

**Comment by jawadalkassim** [comment]
still having the same issue with new release

**Comment by prateekmedia** [comment]
> still having the same issue with new release

That's weird, what's the new issue.

**Comment by jawadalkassim** [comment]
@prateekmedia
```
dell@jawads-laptop ~/Downloads> sudo dnf install harmonoid-linux-x86_64.rpm
[sudo] password for dell:
Last metadata expiration check: 1:57:47 ago on Fri 04 Mar 2022 12:43:29 PM EET.
Error:
 Problem: conflicting requests
  - nothing provides libbitsdojo_window_linux_plugin.so()(64bit) needed by harmonoid-0.2.1-1.x86_64
  - nothing provides libdart_discord_rpc_plugin.so()(64bit) needed by harmonoid-0.2.1-1.x86_64
  - nothing provides libfile_selector_linux_plugin.so()(64bit) needed by harmonoid-0.2.1-1.x86_64
  - nothing provides libflutter_linux_gtk.so()(64bit) needed by harmonoid-0.2.1-1.x86_64
  - nothing provides liboverride_window_destroy_plugin.so()(64bit) needed by harmonoid-0.2.1-1.x86_64
  - nothing provides liburl_launcher_linux_plugin.so()(64bit) needed by harmonoid-0.2.1-1.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
```

**Comment by alexmercerind** [comment]
> @prateekmedia
> 
> ```
> dell@jawads-laptop ~/Downloads> sudo dnf install harmonoid-linux-x86_64.rpm
> [sudo] password for dell:
> Last metadata expiration check: 1:57:47 ago on Fri 04 Mar 2022 12:43:29 PM EET.
> Error:
>  Problem: conflicting requests
>   - nothing provides libbitsdojo_window_linux_plugin.so()(64bit) needed by harmonoid-0.2.1-1.x86_64
>   - nothing provides libdart_discord_rpc_plugin.so()(64bit) needed by harmonoid-0.2.1-1.x86_64
>   - nothing provides libfile_selector_linux_plugin.so()(64bit) needed by harmonoid-0.2.1-1.x86_64
>   - nothing provides libflutter_linux_gtk.so()(64bit) needed by harmonoid-0.2.1-1.x86_64
>   - nothing provides liboverride_window_destroy_plugin.so()(64bit) needed by harmonoid-0.2.1-1.x86_64
>   - nothing provides liburl_launcher_linux_plugin.so()(64bit) needed by harmonoid-0.2.1-1.x86_64
> (try to add '--skip-broken' to skip uninstallable packages)
> ```

Can you try the `.tar.gz` version?

**Comment by jawadalkassim** [comment]
@alexmercerind 
in fedora it's called `mpv-libs-devel` and it's installed
```
dell@jawads-laptop ~/D/harmonoid-linux-x86_64> ./harmonoid 
flutter: Exception: Cannot find libmpv in the usual places. Depending on your distro, you may try installing mpv-devel or libmpv-dev package.
flutter: #0      MPV.initialize (package:libmpv/src/dynamic_library.dart:113)
<asynchronous suspension>
#1      main (package:harmonoid/main.dart:59)
<asynchronous suspension>
```

![Screenshot from 2022-03-04 14-59-36](https://user-images.githubusercontent.com/48631694/156767871-c11a947e-53d3-4bc0-a990-88e291748c9a.png)

**Comment by jawadalkassim** [comment]
```
dell@jawads-laptop ~> sudo dnf search mpv
[sudo] password for dell:
Last metadata expiration check: 2:19:35 ago on Fri 04 Mar 2022 12:43:29 PM EET.
=================================================== Name Exactly Matched: mpv ====================================================
mpv.x86_64 : Movie player playing most video formats and DVDs
================================================== Name & Summary Matched: mpv ===================================================
gnome-mpv.x86_64 : A simple GTK+ frontend for mpv
mpv-libs.x86_64 : Dynamic library for Mpv frontends
mpv-libs-devel.x86_64 : Development package for libmpv
mpv-mpris.x86_64 : MPRIS plugin for mpv
perl-Devel-Dumpvar.noarch : Pure-OO reimplementation of dumpvar.pl
vdr-mpv.x86_64 : A mpv player plugin for VDR
xt7-player-mpv.noarch : Qt/Gambas gui to mpv media player
======================================================= Name Matched: mpv ========================================================
bumpversion.noarch : Version-bump your software with a single command
perl-Dumpvalue.noarch : Screen dump of Perl data
====================================================== Summary Matched: mpv ======================================================
celluloid.x86_64 : A simple GTK+ frontend for mpv
deepin-movie.x86_64 : Deepin movie based on mpv
smplayer.x86_64 : A graphical frontend for mplayer and mpv
```

**Comment by prateekmedia** [comment]
Looks like fedora have different directory to store libmpv

**Comment by 0xj0hn** [comment]
same issue on Arch linux when i build mpv by myself

**Comment by Anshul-004** [comment]
Im facing the same issue infact, it says mpv package isn't installed, while itis.
Any workarounds for now ?
