### ISSUE TITLE
Some files cannot be imported

### ISSUE THREAD

**Issue by Zahrun** [harmonoid/harmonoid#331]
**Describe the bug**

Harmonoid finds 20095 tracks in my music folder but gets stuck on file 8840.
I tried to open directly in tagger and found this:
```
Unhandled exception:
FormatException: Missing extension byte (at offset 7)
#0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1755)
#1      Utf8Decoder.convert (dart:convert/utf.dart:351)
#2      Utf8Codec.decode (dart:convert/utf.dart:63)
#3      Utf8Pointer.toDartString (package:ffi/src/utf8.dart:47)
#4      Tagger._handler (package:media_engine/src/tagger.dart:177)
#5      create.<anonymous closure> (package:media_engine/src/core/initializer.dart:122)
#6      _RootZone.runUnaryGuarded (dart:async/zone.dart:1586)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339)
#8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
#9      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774)
#10     _StreamController._add (dart:async/stream_controller.dart:648)
#11     _StreamController.add (dart:async/stream_controller.dart:596)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192)
```

**To Reproduce**

I’m ok to share the mp3 file in dm if necessary.
I ran this in tagger:
```
parse
file:///uri/where/a/music/file/is/stored.mp3


10000
```

**Expected behavior**

Best case would be that the file gets imported. I can see the metadata in Kid3 and play it in VLC.
Otherwise, generally, maybe it would be good to skip the files which have an error instead of the indexing gets stuck. So that I can import the rest of my library.

**Platform (please complete the following information)**

- OS: Linux
- Version Kubuntu 22.04

**App version**

- Version: v0.3.1

**Comment by alexmercerind** [comment]
Hi @Zahrun!

Thanks for the detailed report, I think you've already followed along the thread at #321.

I'd be helped by the file sample & will be great if you mail me the file at <alexmercerind@gmail.com>.

Still, for further clarification, if you launch the application from your terminal _i.e._ typing `harmonoid` in your terminal, then you should be able to see which fill causes it to get "stuck" (URIs & metadata will be logged).
However, I'm pretty sure that I've implemented a timeout (1 second) if any corrupt file comes in the way.

Thanks!

**Comment by alexmercerind** [comment]
Please don't change the name of the file before mailing.

**Comment by alexmercerind** [comment]
Hi @Zahrun, I've patched this issue & a nightly build is available: https://github.com/harmonoid/nightly/releases/tag/nightly.

Please let me know if the fix works for you & I will release a hot-fix.

The exception is related to native string (`char[]`) on libmpv side being corrupt (or non-null terminated) or maybe Dart's FFI got confused. Anyways.

**Comment by alexmercerind** [comment]
Thanks for the sample!
I just found something really interesting & wanted to share before fix. The exception is because of the `è` character in title metadata field.

When I encode `Les Frères Volfoni` into UTF8 from Dart, the result is like (using two bytes for `è`):
```dart
[76, 101, 115, 32, 70, 114, 195, 168, 114, 101, 115, 32, 86, 111, 108, 102, 111, 110, 105]
```
But libmpv (C API) returns:
```dart
[76, 101, 115, 32, 70, 114, 232, 114, 101, 115, 32, 86, 111, 108, 102, 111, 110, 105]
```

I think two bytes is "correct" standard i.e. `195, 168` (equivalent of `303, 250` in octal, see chart). Two bytes are used for `è`... But mpv is giving 232 (also present in the chart).

I think I should just write a fallback method for such corner cases (by using a simple hashmap & getting character for the byte value).

![](https://user-images.githubusercontent.com/28951144/191094242-33e41484-fffe-4b55-a5cb-a2789908c129.jpg)

https://www.utf8-chartable.de/unicode-utf8-table.pl?utf8=oct&unicodeinhtml=dec

**Comment by alexmercerind** [comment]
Hi @Zahrun!

I made a nightly release again & hopefully this fixes all the issues due to characters with accents. Thanks!

Please try:  https://github.com/harmonoid/nightly/releases/tag/nightly

I hope this can be released as v0.3.2.

**Comment by alexmercerind** [comment]
I have released [v0.3.2](https://github.com/harmonoid/harmonoid/releases/tag/v0.3.2) with the fix. Thanks for the report & sample.

Please re-open if issue still persists.

**Comment by Zahrun** [comment]
20090 files imported into the library.
Even the file which was causing the issue can be played.
I can now actually enjoy the software.
Thank you for your great work @alexmercerind 

I noticed Rhythmbox imports 21220 files from my library.
I will try to find the file format(s) which are not supported and create a separate issue if it does not already exist.
Thank you!

**Comment by alexmercerind** [comment]
Currently these file formats are indexed:
```dart
[
  'OGG',
  'OGA',
  'OGX',
  'AAC',
  'M4A',
  'MP3',
  'WMA',
  'WAV',
  'FLAC',
  'OPUS',
  'AIFF',
  'AC3',
  'ADT',
  'ADTS',
  'AMR',
  'EC3',
  'M3U',
  'M4R',
  'WPL',
  'ZPL',
];
```

I think list is quite complete, still feel free to share what you feel is missing from it.

**Comment by Zahrun** [comment]
I have found 2 aif files, 2 mpeg, 4 webm, 1 mov, 10 mp4, and the rest are wav files.
They don’t really need to be in Harmonoid. I can convert these also.
I leave it to you. I don’t think it is required to add these supports.
Thanks
