### ISSUE TITLE
Error on opening - 

### ISSUE THREAD

**Issue by viveksreedharan88** [harmonoid/harmonoid#452]
**Describe the bug**

I am getting the below error on opening Harmonoid,

Exception: PathAccessException: Exists failed, path = '/media/vivek/VIVEK/Devotional' (OS Error: Permission denied, errno = 13)
Stack trace: #0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _Directory.exists.<anonymous closure> (dart:io/directory_impl.dart:84)
<asynchronous suspension>
#2      MediaLibrary.register (package:media_library/src/media_library.dart:124)
<asynchronous suspension>
#3      Collection.initialize (package:harmonoid/core/collection.dart:46)
<asynchronous suspension>
#4      main (package:harmonoid/main.dart:162)
<asynchronous suspension>

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Version [e.g. v0.2.1]

**Smartphone (please complete the following information):**
 - Version [e.g. v0.2.1]

**Comment by alexmercerind** [comment]
Fixed in the latest release.

**Comment by wefalltomorrow** [comment]
> Fixed in the latest release.

Still occurs for me sadly
