### ISSUE TITLE
Error PathNotFoundException

### ISSUE THREAD

**Issue by 0ptiKali1usion** [harmonoid/harmonoid#462]
Exception: PathNotFoundException: Exists failed, path = '\\?\M:\Shared Music' (OS Error: The network path was not found.
, errno = 53)
Stack trace: #0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _Directory.exists.<anonymous closure> (dart:io/directory_impl.dart:84)
<asynchronous suspension>
#2      MediaLibrary.register (package:media_library/src/media_library.dart:124)
<asynchronous suspension>
#3      Collection.initialize (package:harmonoid/core/collection.dart:46)
<asynchronous suspension>
#4      main (package:harmonoid/main.dart:162)
<asynchronous suspension>

________________________________________
I basically had a network drive with music files, mapped. I unmapped it. Harmonoid gave me this ugly error message. I assume now that you know, you will make a new, prettified error message :-) with less raw code & debug stuff.
_________________________________________

1. Go to map a network share of music to a letter drive, in Microsoft Windows
2. Use harmonoid to play music.
3. quit and relaunch, after unmapping drive.
4. and that should do it, I think.

you should see what I sent you, in a harmonoid launch window.

i expected to rock out with my Spock out,

**Platform (please complete the following information)**

- OS: Windows 10
- Version 10.0.19045.3570
**App version**
it says version 1.0, 256k filesize, in Properties -> Details
Please confirm that you're on the latest version available.

- Version: 0.3.8.0 I guess is what it really is.
Have a nice day!
![harmonoid_crash](https://github.com/harmonoid/harmonoid/assets/97764916/bf5ad983-a66f-46e5-9957-15e0ad55df02)

**Comment by alexmercerind** [comment]
Hi!

Thanks for the details. As a workaround, you may edit the `C:\Users\XYZ\.Harmonoid\Configuration.JSON` using Notepad to remove your network drive.

**Comment by alexmercerind** [comment]
Try the latest release please.
