### ISSUE TITLE
Harmonoid bugging out system both in kde and hyprland

### ISSUE THREAD

**Issue by zakgdg** [harmonoid/harmonoid#484]
**Describe the issue**

Sometimes I open harmonoid to listen then it bugs out my entire desktop and freezes the computer and I have to force restart to fix the issue

**Attach logs**
(harmonoid:220762): Gtk-WARNING **: 15:59:13.048: Theme parsing error: gtk-dark.css:2553:51: Using one color stop with linear-gradient() is deprecated.
flutter: Linux 6.10.7-200.fsync.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC TKG Wed Sep  4 04:41:43 UTC 2024
flutter: null
flutter: {collectionDirectories: [/home/zakariya/Music], language: {code: en_US, name: English, country: United States}, themeMode: 2, automaticAccent: false, notificationLyrics: true, collectionSearchRecent: [], webRecent: [], taskbarIndicator: false, seamlessPlayback: false, jumpToNowPlayingScreenOnPlay: true, automaticMusicLookup: false, dynamicNowPlayingBarColoring: true, modernNowPlayingScreen: true, modernNowPlayingScreenCarouselIndex: 5, lyricsVisible: true, discordRPC: true, highlightedLyricsSize: 38.0, unhighlightedLyricsSize: 14.0, albumsSort: 3, tracksSort: 0, artistsSort: 0, genresSort: 0, albumsOrderType: 0, tracksOrderType: 0, artistsOrderType: 0, genresOrderType: 0, minimumFileSize: 1048576, libraryTab: 3, useLRCFromTrackDirectory: false, lookupForFallbackAlbumArt: true, displayAudioFormat: true, mobileDisplayVolumeSliderDirectlyOnNowPlayingScreen: true, mobileEnableNowPlayingScreenRippleEffect: true, mobileAlbumsGridSize: 2, mobileArtistsGridSize: 3, mobileGenresGridSize: 3, albumHashCodeParameters: [0], userLibmpvOptions: {}, disableAnimations: false, addLibraryToPlaylistWhenPlayingFromTracksTab: false, fallbackAlbumArtFileNames: [Folder.jpg, Folder.png, AlbumArtSmall.jpg, AlbumArt.jpg, Album.jpg, .folder.png, cover.jpg, cover.png, cover.gif, front.jpg, front.png, front.gif, front.bmp, thumb.jpg], androidEnableVolumeBoostFilter: false, animationDuration: {fast: 150, medium: 300, slow: 450}}
flutter: 10812
flutter: PathNotFoundException: Deletion failed, path = '/home/zakariya/.Harmonoid/Albums.JSON' (OS Error: No such file or directory, errno = 2)
flutter: #0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _Directory._delete.<anonymous closure> (dart:io/directory_impl.dart:185)
<asynchronous suspension>
#2      FileSystemEntityExtension.delete_ (package:safe_local_storage/file_system.dart:495)
<asynchronous suspension>
#3      SafeLocalStorage._delete (package:safe_local_storage/safe_local_storage.dart:239)
<asynchronous suspension>
#4      SafeLocalStorage.delete.<anonymous closure> (package:safe_local_storage/safe_local_storage.dart:150)
<asynchronous suspension>
#5      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:33)
<asynchronous suspension>
#6      Helpers.unlinkLegacyCacheFiles (package:media_library/src/helpers.dart:72)
<asynchronous suspension>
#7      _spawn (package:media_library/src/isolates.dart:151)
<asynchronous suspension>

flutter: PathNotFoundException: Deletion failed, path = '/home/zakariya/.Harmonoid/Artists.JSON' (OS Error: No such file or directory, errno = 2)
flutter: #0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _Directory._delete.<anonymous closure> (dart:io/directory_impl.dart:185)
<asynchronous suspension>
#2      FileSystemEntityExtension.delete_ (package:safe_local_storage/file_system.dart:495)
<asynchronous suspension>
#3      SafeLocalStorage._delete (package:safe_local_storage/safe_local_storage.dart:239)
<asynchronous suspension>
#4      SafeLocalStorage.delete.<anonymous closure> (package:safe_local_storage/safe_local_storage.dart:150)
<asynchronous suspension>
#5      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:33)
<asynchronous suspension>
#6      Helpers.unlinkLegacyCacheFiles (package:media_library/src/helpers.dart:80)
<asynchronous suspension>
#7      _spawn (package:media_library/src/isolates.dart:151)
<asynchronous suspension>

flutter: PathNotFoundException: Deletion failed, path = '/home/zakariya/.Harmonoid/Genres.JSON' (OS Error: No such file or directory, errno = 2)
flutter: #0      _checkForErrorResponse (dart:io/common.dart:55)
#1      _Directory._delete.<anonymous closure> (dart:io/directory_impl.dart:185)
<asynchronous suspension>
#2      FileSystemEntityExtension.delete_ (package:safe_local_storage/file_system.dart:495)
<asynchronous suspension>
#3      SafeLocalStorage._delete (package:safe_local_storage/safe_local_storage.dart:239)
<asynchronous suspension>
#4      SafeLocalStorage.delete.<anonymous closure> (package:safe_local_storage/safe_local_storage.dart:150)
<asynchronous suspension>
#5      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:33)
<asynchronous suspension>
#6      Helpers.unlinkLegacyCacheFiles (package:media_library/src/helpers.dart:88)
<asynchronous suspension>
#7      _spawn (package:media_library/src/isolates.dart:151)
<asynchronous suspension>

flutter: _tracks: 27
flutter: _albums: 17
flutter: _artists: 24
flutter: _genres: 1
flutter: albumArtists: 16
flutter: [Lyrics]: (custom) File: '/home/zakariya/.Harmonoid/Lyrics/Shinrog-InfertehnoUnknownAlbumXmillsa'
flutter: [Lyrics]: Configuration.instance.useLRCFromTrackDirectory: false
flutter: [Lyrics]: (API) Shinrog - Infertehno Xmillsa
flutter: [Monitor(workarea: Rect.fromLTRB(0.0, 0.0, 1920.0, 1080.0), bounds: Rect.fromLTRB(0.0, 0.0, 1920.0, 1080.0))]
flutter: [NowPlayingBar] Freed 1 [Color] [TweenAnimationBuilder] fill(s).
flutter: #1 draw: AssetImage(bundle: null, name: "assets/preloaded_visuals/0.webp")
flutter: #1 draw: AssetImage(bundle: null, name: "assets/preloaded_visuals/1.webp")
flutter: file:///home/zakariya/Music/Spectrum%20Sounds%20-%20F-777%20_%20He's%20a%20Pirate.mp3
flutter: Tags(uri: file:///home/zakariya/Music/Spectrum%20Sounds%20-%20F-777%20_%20He's%20a%20Pirate.mp3, trackName: F-777 : He's a Pirate, albumName: null, trackNumber: null, discNumber: null, albumLength: 1, albumArtistName: Spectrum Sounds, trackArtistNames: [Spectrum Sounds], authorNames: null, writerNames: null, year: null, genres: null, lyrics: null, timeAdded: 2024-08-03 21:32:32.000, duration: 0:00:00.000000, bitrate: 0)
flutter: file:///home/zakariya/Music/Dimrain47%20-%20The%20Falling%20Mysts.mp3
flutter: Tags(uri: file:///home/zakariya/Music/Dimrain47%20-%20The%20Falling%20Mysts.mp3, trackName: The Falling Mysts, albumName: The Dimrain47 Collection (2005-2012), trackNumber: null, discNumber: null, albumLength: 1, albumArtistName: Dimrain47, trackArtistNames: [Dimrain47], authorNames: null, writerNames: null, year: null, genres: null, lyrics: null, timeAdded: 2024-08-03 21:33:03.000, duration: 0:00:00.000000, bitrate: 0)
flutter: file:///home/zakariya/Music/ColBreakz%20-%2040.000.mp3
flutter: Tags(uri: file:///home/zakariya/Music/ColBreakz%20-%2040.000.mp3, trackName: 40.000, albumName: 40.000, trackNumber: null, discNumber: null, albumLength: 1, albumArtistName: ColBreakz, trackArtistNames: [ColBreakz], authorNames: null, writerNames: null, year: null, genres: null, lyrics: null, timeAdded: 2024-08-03 21:33:38.000, duration: 0:00:00.000000, bitrate: 0)
flutter: file:///home/zakariya/Music/Xmillsa%20-%20nubbinownz%20-%20These%20Mistakes%20are%20Mine%20Alone.mp3
flutter: Tags(uri: file:///home/zakariya/Music/Xmillsa%20-%20nubbinownz%20-%20These%20Mistakes%20are%20Mine%20Alone.mp3, trackName: nubbinownz - These Mistakes are Mine Alone, albumName: null, trackNumber: null, discNumber: null, albumLength: 1, albumArtistName: Xmillsa, trackArtistNames: [Xmillsa], authorNames: null, writerNames: null, year: null, genres: null, lyrics: null, timeAdded: 2024-08-03 21:34:06.000, duration: 0:00:00.000000, bitrate: 0)
flutter: file:///home/zakariya/Music/Dimrain47%20-%20Dimrain47%20-%20(7)%20Forsaken%20Neon.mp3
flutter: Tags(uri: file:///home/zakariya/Music/Dimrain47%20-%20Dimrain47%20-%20(7)%20Forsaken%20Neon.mp3, trackName: Dimrain47 - (7) Forsaken Neon, albumName: null, trackNumber: null, discNumber: null, albumLength: 1, albumArtistName: Dimrain47, trackArtistNames: [Dimrain47], authorNames: null, writerNames: null, year: null, genres: null, lyrics: null, timeAdded: 2024-08-03 21:34:24.000, duration: 0:00:00.000000, bitrate: 0)
flutter: file:///home/zakariya/Music/2KE%20&%20808iuli%20-%20X-SLIDE%20(Slowed).mp3
flutter: Tags(uri: file:///home/zakariya/Music/2KE%20&%20808iuli%20-%20X-SLIDE%20(Slowed).mp3, trackName: X-SLIDE (Slowed), albumName: X-SLIDE, trackNumber: null, discNumber: null, albumLength: 1, albumArtistName: 2KE & 808iuli, trackArtistNames: [2KE & 808iuli], authorNames: null, writerNames: null, year: null, genres: null, lyrics: null, timeAdded: 2024-08-07 19:27:35.000, duration: 0:00:00.000000, bitrate: 0)
flutter: file:///home/zakariya/Music/Waterflame%20-%20Electroman%20Adventures.mp3
flutter: Tags(uri: file:///home/zakariya/Music/Waterflame%20-%20Electroman%20Adventures.mp3, trackName: Electroman Adventures, albumName: Community Favorites, trackNumber: null, discNumber: null, albumLength: 1, albumArtistName: Waterflame, trackArtistNames: [Waterflame], authorNames: null, writerNames: null, year: null, genres: null, lyrics: null, timeAdded: 2024-08-10 13:31:48.000, duration: 0:00:00.000000, bitrate: 0)
flutter: file:///home/zakariya/Music/DeoxysPrime%20-%20Ending%20~%20A%20Hero%20Returns%20-%20Mega%20Man%207%20%5BOST%5D.mp3
flutter: Tags(uri: file:///home/zakariya/Music/DeoxysPrime%20-%20Ending%20~%20A%20Hero%20Returns%20-%20Mega%20Man%207%20%5BOST%5D.mp3, trackName: Ending ~ A Hero Returns - Mega Man 7 [OST], albumName: null, trackNumber: null, discNumber: null, albumLength: 1, albumArtistName: DeoxysPrime, trackArtistNames: [DeoxysPrime], authorNames: null, writerNames: null, year: null, genres: null, lyrics: null, timeAdded: 2024-08-15 22:50:14.000, duration: 0:00:00.000000, bitrate: 0)
flutter: file:///home/zakariya/Music/Xmillsa%20-%20Shinrog%20-%20Infertehno.mp3
flutter: Tags(uri: file:///home/zakariya/Music/Xmillsa%20-%20Shinrog%20-%20Infertehno.mp3, trackName: Shinrog - Infertehno, albumName: null, trackNumber: null, discNumber: null, albumLength: 1, albumArtistName: Xmillsa, trackArtistNames: [Xmillsa], authorNames: null, writerNames: null, year: null, genres: null, lyrics: null, timeAdded: 2024-08-16 17:06:04.000, duration: 0:00:00.000000, bitrate: 0)
flutter: file:///home/zakariya/Music/Deleted%20NCS%20-%20Circle%20Spectrum%20-%20Andromedik%20-%20Firefly%20%5BPrivated%20NCS%20Release%5D.mp3
flutter: Tags(uri: file:///home/zakariya/Music/Deleted%20NCS%20-%20Circle%20Spectrum%20-%20Andromedik%20-%20Firefly%20%5BPrivated%20NCS%20Release%5D.mp3, trackName: Andromedik - Firefly [Privated NCS Release], albumName: null, trackNumber: null, discNumber: null, albumLength: 1, albumArtistName: Deleted NCS - Circle Spectrum, trackArtistNames: [Deleted NCS - Circle Spectrum], authorNames: null, writerNames: null, year: null, genres: null, lyrics: null, timeAdded: 2024-08-18 22:40:17.000, duration: 0:00:00.000000, bitrate: 0)
flutter: file:///home/zakariya/Music/BurgeraX%20-%20BurgeraX_%20Scorpion%20%5BDrum%20&%20Bass%5D.mp3
flutter: Tags(uri: file:///home/zakariya/Music/BurgeraX%20-%20BurgeraX_%20Scorpion%20%5BDrum%20&%20Bass%5D.mp3, trackName: BurgeraX: Scorpion [Drum & Bass], albumName: null, trackNumber: null, discNumber: null, albumLength: 1, albumArtistName: BurgeraX, trackArtistNames: [BurgeraX], authorNames: null, writerNames: null, year: null, genres: null, lyrics: null, timeAdded: 2024-08-18 22:40:29.000, duration: 0:00:00.000000, bitrate: 0)
flutter: file:///home/zakariya/Music/ColBreakz%20-%202011.mp3
flutter: Tags(uri: file:///home/zakariya/Music/ColBreakz%20-%202011.mp3, trackName: 2011, albumName: 2011, trackNumber: null, discNumber: null, albumLength: 1, albumArtistName: ColBreakz, trackArtistNames: [ColBreakz], authorNames: null, writerNames: null, year: null, genres: null, lyrics: null, timeAdded: 2024-08-18 22:40:40.000, duration: 0:00:00.000000, bitrate: 0)
flutter: file:///home/zakariya/Music/Skyward%20-%20cYsmix%20-%20Peer%20Gynt.mp3
flutter: Tags(uri: file:///home/zakariya/Music/Skyward%20-%20cYsmix%20-%20Peer%20Gynt.mp3, trackName: cYsmix - Peer Gynt, albumName: null, trackNumber: null, discNumber: null, albumLength: 1, albumArtistName: Skyward, trackArtistNames: [Skyward], authorNames: null, writerNames: null, year: null, genres: null, lyrics: null, timeAdded: 2024-08-18 22:41:06.000, duration: 0:00:00.000000, bitrate: 0)
flutter: file:///home/zakariya/Music/Desmeon%20-%20Undone.mp3
flutter: Tags(uri: file:///home/zakariya/Music/Desmeon%20-%20Undone.mp3, trackName: Undone, albumName: NCS is Love, NCS is Life, Vol. 1, trackNumber: null, discNumber: null, albumLength: 1, albumArtistName: Desmeon, trackArtistNames: [Desmeon], authorNames: null, writerNames: null, year: null, genres: null, lyrics: null, timeAdded: 2024-09-09 21:10:24.000, duration: 0:00:00.000000, bitrate: 0)
flutter: file:///home/zakariya/Music/Aero%20Chord%20-%20Time%20Leap.mp3
flutter: Tags(uri: file:///home/zakariya/Music/Aero%20Chord%20-%20Time%20Leap.mp3, trackName: Time Leap, albumName: Time Leap, trackNumber: null, discNumber: null, albumLength: 1, albumArtistName: Aero Chord, trackArtistNames: [Aero Chord], authorNames: null, writerNames: null, year: null, genres: null, lyrics: null, timeAdded: 2024-09-09 21:10:47.000, duration: 0:00:00.000000, bitrate: 0)
flutter: file:///home/zakariya/Music/Anikdote%20-%20Turn%20It%20Up.mp3
flutter: Tags(uri: file:///home/zakariya/Music/Anikdote%20-%20Turn%20It%20Up.mp3, trackName: Turn It Up, albumName: Turn It Up, trackNumber: null, discNumber: null, albumLength: 1, albumArtistName: Anikdote, trackArtistNames: [Anikdote], authorNames: null, writerNames: null, year: null, genres: null, lyrics: null, timeAdded: 2024-09-09 21:11:16.000, duration: 0:00:00.000000, bitrate: 0)
flutter: file:///home/zakariya/Music/Andromedik%20-%20Let%20Me%20In.mp3
flutter: Tags(uri: file:///home/zakariya/Music/Andromedik%20-%20Let%20Me%20In.mp3, trackName: Let Me In, albumName: Let Me In, trackNumber: null, discNumber: null, albumLength: 1, albumArtistName: Andromedik, trackArtistNames: [Andromedik], authorNames: null, writerNames: null, year: null, genres: null, lyrics: null, timeAdded: 2024-09-09 21:12:05.000, duration: 0:00:00.000000, bitrate: 0)
flutter: file:///home/zakariya/Music/Robin%20Hustin%20&%20Tobimorrow%20-%20Light%20It%20Up.mp3
flutter: Tags(uri: file:///home/zakariya/Music/Robin%20Hustin%20&%20Tobimorrow%20-%20Light%20It%20Up.mp3, trackName: Light It Up, albumName: Light It Up, trackNumber: null, discNumber: null, albumLength: 1, albumArtistName: Robin Hustin & Tobimorrow, trackArtistNames: [Robin Hustin & Tobimorrow], authorNames: null, writerNames: null, year: null, genres: null, lyrics: null, timeAdded: 2024-09-09 21:12:26.000, duration: 0:00:00.000000, bitrate: 0)
flutter: file:///home/zakariya/Music/Unknown%20Brain%20&%20Rival%20-%20Control.mp3
flutter: Tags(uri: file:///home/zakariya/Music/Unknown%20Brain%20&%20Rival%20-%20Control.mp3, trackName: Control, albumName: Control, trackNumber: null, discNumber: null, albumLength: 1, albumArtistName: Unknown Brain & Rival, trackArtistNames: [Unknown Brain & Rival], authorNames: null, writerNames: null, year: null, genres: null, lyrics: null, timeAdded: 2024-09-09 21:12:39.000, duration: 0:00:00.000000, bitrate: 0)
flutter: file:///home/zakariya/Music/3rd%20Prototype%20-%20Feel%20So%20Good.mp3
flutter: Tags(uri: file:///home/zakariya/Music/3rd%20Prototype%20-%20Feel%20So%20Good.mp3, trackName: Feel So Good, albumName: Feel So Good, trackNumber: null, discNumber: null, albumLength: 1, albumArtistName: 3rd Prototype, trackArtistNames: [3rd Prototype], authorNames: null, writerNames: null, year: null, genres: null, lyrics: null, timeAdded: 2024-09-09 21:12:59.000, duration: 0:00:00.000000, bitrate: 0)
flutter: file:///home/zakariya/Music/Cartoon,%20J%C3%A9ja,%20Mikk%20M%C3%A4e,%20&%20Futuristik%20-%20C%20U%20Again.mp3
flutter: Tags(uri: file:///home/zakariya/Music/Cartoon,%20J%C3%A9ja,%20Mikk%20M%C3%A4e,%20&%20Futuristik%20-%20C%20U%20Again.mp3, trackName: C U Again, albumName: NCS: The Best of 2016, trackNumber: null, discNumber: null, albumLength: 1, albumArtistName: Cartoon, Jéja, Mikk Mäe, & Futuristik, trackArtistNames: [Cartoon, Jéja, Mikk Mäe, & Futuristik], authorNames: null, writerNames: null, year: null, genres: null, lyrics: null, timeAdded: 2024-09-09 21:13:36.000, duration: 0:00:00.000000, bitrate: 0)
flutter: file:///home/zakariya/Music/Disfigure%20&%20Tara%20Louise%20-%20Blank.mp3
flutter: Tags(uri: file:///home/zakariya/Music/Disfigure%20&%20Tara%20Louise%20-%20Blank.mp3, trackName: Blank, albumName: NCS: The Best of 2015, trackNumber: null, discNumber: null, albumLength: 1, albumArtistName: Disfigure & Tara Louise, trackArtistNames: [Disfigure & Tara Louise], authorNames: null, writerNames: null, year: null, genres: null, lyrics: null, timeAdded: 2024-09-09 21:14:12.000, duration: 0:00:00.000000, bitrate: 0)
flutter: file:///home/zakariya/Music/Aero%20Chord%20&%20Ddark%20-%20Shootin%20Stars.mp3
flutter: Tags(uri: file:///home/zakariya/Music/Aero%20Chord%20&%20Ddark%20-%20Shootin%20Stars.mp3, trackName: Shootin Stars, albumName: Shootin Stars, trackNumber: null, discNumber: null, albumLength: 1, albumArtistName: Aero Chord & Ddark, trackArtistNames: [Aero Chord & Ddark], authorNames: null, writerNames: null, year: null, genres: null, lyrics: null, timeAdded: 2024-09-09 22:51:34.000, duration: 0:00:00.000000, bitrate: 0)
flutter: file:///home/zakariya/Music/LapFox%20Trax%20Archives%20-%20Furries%20in%20a%20Blender%20-%20Storm%20World%20(Storm%20Trax%20EP).mp3
flutter: Tags(uri: file:///home/zakariya/Music/LapFox%20Trax%20Archives%20-%20Furries%20in%20a%20Blender%20-%20Storm%20World%20(Storm%20Trax%20EP).mp3, trackName: Furries in a Blender - Storm World (Storm Trax EP), albumName: null, trackNumber: null, discNumber: null, albumLength: 1, albumArtistName: LapFox Trax Archives, trackArtistNames: [LapFox Trax Archives], authorNames: null, writerNames: null, year: null, genres: null, lyrics: null, timeAdded: 2024-09-11 19:46:02.000, duration: 0:00:00.000000, bitrate: 0)
flutter: file:///home/zakariya/Music/OcularNebula%20-%20Stay%20Inside%20Me.mp3
flutter: Tags(uri: file:///home/zakariya/Music/OcularNebula%20-%20Stay%20Inside%20Me.mp3, trackName: Stay Inside Me, albumName: null, trackNumber: null, discNumber: null, albumLength: 1, albumArtistName: OcularNebula, trackArtistNames: [OcularNebula], authorNames: null, writerNames: null, year: null, genres: null, lyrics: null, timeAdded: 2024-09-11 20:44:18.000, duration: 0:00:00.000000, bitrate: 0)
flutter: file:///home/zakariya/Music/Erbil%20Davulcu%20-%20Machinae%20Supremacy%20-%20Sidology%20Episode%202%20-%20Trinity%20Official%20Soundtrack.mp3
flutter: Tags(uri: file:///home/zakariya/Music/Erbil%20Davulcu%20-%20Machinae%20Supremacy%20-%20Sidology%20Episode%202%20-%20Trinity%20Official%20Soundtrack.mp3, trackName: Machinae Supremacy - Sidology Episode 2 - Trinity Official Soundtrack, albumName: null, trackNumber: null, discNumber: null, albumLength: 1, albumArtistName: Erbil Davulcu, trackArtistNames: [Erbil Davulcu], authorNames: null, writerNames: null, year: null, genres: null, lyrics: null, timeAdded: 2024-09-12 10:40:56.000, duration: 0:00:00.000000, bitrate: 0)
flutter: file:///home/zakariya/Music/Light%20Years%20Away%20-%20Melrose%20At%20Midnight.mp3
flutter: Tags(uri: file:///home/zakariya/Music/Light%20Years%20Away%20-%20Melrose%20At%20Midnight.mp3, trackName: Melrose At Midnight, albumName: Melrose At Midnight, trackNumber: null, discNumber: null, albumLength: 1, albumArtistName: Light Years Away, trackArtistNames: [Light Years Away], authorNames: null, writerNames: null, year: null, genres: null, lyrics: null, timeAdded: 2024-09-15 21:38:41.000, duration: 0:00:00.000000, bitrate: 0)
flutter: PathNotFoundException: Cannot create file, path = '/home/zakariya/.config/com.alexmercerind.harmonoid/WindowState.JSON' (OS Error: No such file or directory, errno = 2)
flutter: #0      _checkForErrorResponse (dart:io/common.dart:55)
flutter: #1      _File.create.<anonymous closure> (dart:io/file_impl.dart:286)
flutter: <asynchronous suspension>
flutter: #2      FileExtension.write_.<anonymous closure> (package:safe_local_storage/file_system.dart:231)
flutter: <asynchronous suspension>
flutter: #3      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:33)
flutter: <asynchronous suspension>
flutter: #4      SafeLocalStorage.write (package:safe_local_storage/safe_local_storage.dart:30)
flutter: <asynchronous suspension>
flutter: #5      WindowState.save (package:window_plus/src/window_state.dart:96)
flutter: <asynchronous suspension>
flutter: #6      GTKWindow.methodCallHandler (package:window_plus/src/platform/gtk_window.dart:82)
flutter: <asynchronous suspension>
flutter: #7      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:550)
flutter: <asynchronous suspension>
flutter: #8      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:393)
flutter: <asynchronous suspension>
flutter: 
[FATAL:flutter/fml/thread_local.cc(32)] Check failed: false. pthread_setspecific failed (22): Invalid argument
[1]    220762 IOT instruction (core dumped)  harmonoid

**Platform (please complete the following information)**
- OS: Linux
- Version: Nobara 40
**App version**
- Version[0.3.8]

**Comment by alexmercerind** [comment]
Hello @zakgdg,

Do things bug out during app's runtime or right away as soon as you open the app?

**Comment by TuxManxD** [comment]
@alexmercerind so it happens in the app's runtime

**Comment by alexmercerind** [comment]
There's a high possibility that this is an issue with your GNU/Linux setup. I have seen it numerous times before.

**Comment by TuxManxD** [comment]
@alexmercerind I wish I can describe the issue with a video but since the pc is in an unusable state I can't do anything :/

**Comment by alexmercerind** [comment]
I really can't guess.

**Comment by alexmercerind** [comment]
But you can try latest snapshot build: https://github.com/harmonoid/snapshots/releases/snapshot

Pretty much everything is re-written & improved.
